Repository hackmcgill/mchacks6, pull requests merged in 2018-10, with the labels that each got.

#46 Fix sponsor hero graphic sizing
  src/sponsor.html
  src/style/sponsor.scss
  yarn.lock
Labels: page: sponsor

#48 Fix sticky header in sponsor page
  src/style/index.scss
  src/style/main.scss
Labels: page: sponsor

#53 Add Code of Conduct
  src/conduct.html
  src/index.html
  src/style/conduct.scss
  src/style/index.scss
  src/style/main.scss
Labels: chore, copy

#55 Add facebook messenger bot
  src/index.html
Labels: enhancement
