Repository hackmcgill/mchacks6, pull requests merged in 2018-11, with the labels that each got.

#59 add header and footer to code of conduct
  src/code-of-conduct.html
  src/conduct.html
  src/style/conduct.scss
Labels: chore

#58 FAQ section
  .eslintrc.js
  src/index.html
  src/js/accordion.js
  src/js/app.js
  src/static/faq-symbols-left.svg
  src/static/faq-symbols-right.svg
  src/static/faq-symbols.svg
  src/static/sponsors/minus.svg
  src/static/sponsors/plus.svg
  src/style/index.scss
Labels: page: landing

#69 Style changes to navbar and footer
  src/style/index.scss
  src/style/nav.scss
Labels: chore, design

#72 Move Github templates out of folder
  .github/bug_report.md
  .github/feature_request.md
  .github/pull_request_template.md
Labels: chore

#70 FAQ edits
  src/js/accordion.js
  src/style/index.scss
Labels: page: landing

#73 Small fixes to landing page
  src/index.html
  src/style/index.scss
  src/style/nav.scss
Labels: page: landing
